### PR TITLE
declare libjpeg dep

### PR DESCRIPTION
**Pull request by mfansler**
Adds explicitly `libjpeg` dependency. Since [`r-base=4.1` has not yet migrated](https://github.com/conda-forge/r-base-feedstock/pull/243), we split the declaration via variants.

## Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Partially addresses #18.

### CODE REVIEW

**Comment by mfansler** [comment]
@conda-forge-admin please rerender

**Comment by mfansler** [comment]
The linter failure is expected, due to open bug: https://github.com/conda-forge/conda-smithy/issues/1726.

**Comment by mfansler** [comment]
@conda-forge-admin please rerender

**Comment by mfansler** [comment]
Seeing clobber warnings both from this build (seems like vendoring deps) and from `libjpeg-turbo` + `jpeg` coinstallation.

**Comment by mfansler** [comment]
@conda-forge-admin please rerender

**Comment by mfansler** [comment]
@conda-forge-admin please rerender

**Comment by hmaarrfk** [comment]
copy in the migration file for jpeg9->jpeg turbo. it adds a stricter pin on turbo with the exclusion

**Comment by hmaarrfk** [comment]
The transition isn't super easy... yet, see final point https://github.com/conda-forge/conda-forge.github.io/issues/673#issuecomment-1469925874

**Comment by mfansler** [comment]
@conda-forge-admin please rerender

**Comment by mfansler** [comment]
@hmaarrfk thanks for the quick reply! Where should I copy it to? I tried [`.ci_support/migrations/`](https://github.com/conda-forge/r-cairo-feedstock/pull/19/commits/aefea69f3e58381a1e07e8e06cd39ae3ce246c97), but rerender bot found nothing to do. I expect it should update the pins in the `.ci_support/*.yaml` files.

**Comment by hmaarrfk** [comment]
Try: https://github.com/mfansler/r-cairo-feedstock/pull/1

**Comment by hmaarrfk** [comment]
lets see what happens in https://github.com/conda-forge/r-cairo-feedstock/pull/20

**Pull request merged**
